---
- name: Install nginx on webservers
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Strat nginx
      service:
        name: nginx
        state: started
       
    - name: Deploy webpage
      copy:
        src: /home/ubuntu/Downloads/index.html
        dest: /var/www/html
